"""Generate structural TS and JSON Schema from this package's pinned OpenAPI.
Requires Python 3 and PyYAML. No network access or remote schema resolution.
Runtime constraints stay in JSON Schema; TS is not a validator/HTTP SDK.
"""
from pathlib import Path
import copy, hashlib, json
import yaml
P=Path(__file__).resolve().parent
from check_contracts import check
check(P.parent.parent)
raw=(P/'openapi.baseline.yaml').read_bytes()
api=yaml.safe_load(raw)
schemas=api['components']['schemas']
allowed={'type','format','minLength','maxLength','required','additionalProperties','properties','items','description','$ref','enum','anyOf','oneOf','allOf','minItems','minimum','maximum','exclusiveMinimum','exclusiveMaximum','uniqueItems','pattern','not','maxItems','prefixItems','discriminator','title','default','examples','example','readOnly','writeOnly','deprecated','const'}
def q(v):return json.dumps(v,ensure_ascii=False)
def typ(s):
 if s is True:return 'unknown'
 if s is False:return 'never'
 unknown=set(s)-allowed
 if unknown: raise ValueError(f'Unsupported schema keys: {unknown}')
 if '$ref' in s:return s['$ref'].split('/')[-1]
 if 'const' in s:return q(s['const'])
 if 'enum' in s:return ' | '.join(q(v) for v in s['enum'])
 if s.get('type')=='object':
  if 'oneOf' in s:
   variants=[]
   for b in s['oneOf']:
    if set(b)-{'required','not'}:raise ValueError('Unsupported object branch')
    v=copy.deepcopy(s);v.pop('oneOf');v['required']=list(set(s.get('required',[]))|set(b.get('required',[])))
    forbidden=b.get('not',{}).get('required',[])
    if len(forbidden)>1:raise ValueError('Unsupported not conjunction')
    for f in forbidden:v['properties'][f]=False
    variants.append(typ(v))
   return '('+' | '.join(variants)+')'
  req=set(s.get('required',[])); rows=[q(k)+('' if k in req else '?')+': '+typ(v)+';' for k,v in s.get('properties',{}).items()]
  ap=s.get('additionalProperties',False)
  if ap is not False: rows.append('[key: string]: '+('unknown' if ap is True else typ(ap))+';')
  return '{ '+ ' '.join(rows)+' }'
 for union in ['oneOf','anyOf','allOf']:
  if union in s:return '('+(' & ' if union=='allOf' else ' | ').join(typ(v) for v in s[union])+')'
 t=s.get('type')
 if t=='string':return 'string'
 if t in ('integer','number'):return 'number'
 if t=='boolean':return 'boolean'
 if t=='null':return 'null'
 if t=='array':
  if 'prefixItems' in s:
   if s.get('items') is not False or s.get('minItems')!=len(s['prefixItems']) or s.get('maxItems')!=len(s['prefixItems']):raise ValueError('Unsupported variable tuple')
   return '['+', '.join(typ(v) for v in s['prefixItems'])+']'
  return 'Array<'+typ(s.get('items',True))+'>'
 if not s:return 'unknown'
 raise ValueError('Unsupported schema '+str(s))
def rewrite(v):
 if isinstance(v,dict):return {k:rewrite(w) for k,w in v.items()}
 if isinstance(v,list):return [rewrite(w) for w in v]
 if isinstance(v,str) and v.startswith('#/components/schemas/'):return v.replace('#/components/schemas/','#/$defs/',1)
 return v
hash_=hashlib.sha256(raw).hexdigest()
bundle={'$schema':'https://json-schema.org/draft/2020-12/schema','$id':'urn:roadguard:api:fe-r3-v1','title':'RoadGuard API definitions from proposed R3 baseline','$comment':'Select a DTO using a root $ref into $defs; this bundle root alone does not validate a DTO. Source SHA256 '+hash_,'$defs':rewrite(schemas)}
(P/'api.schemas.json').write_text(json.dumps(bundle,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
lines=['// GENERATED by build_contracts.py from openapi.baseline.yaml. Do not edit.','// Source SHA256: '+hash_,'// Structural TS only: use JSON Schema for formats/ranges/oneOf and runtime validation.','']
for name,s in schemas.items():
 if s.get('description'):lines.append('/** '+s['description'].replace('*/','* /')+' */')
 lines.append('export type '+name+' = '+typ(s)+';\n')
(P/'api.types.ts').write_text('\n'.join(lines),encoding='utf-8')
rows=['# RoadGuard — Operation catalog từ baseline','', 'Nguồn đề xuất R3; path tính từ `/api/v1`. Catalog sinh tự động, không chứng minh endpoint đã triển khai.','', '| Operation ID | Method / path | Role | Request schema | Success schema | Required headers |','|---|---|---|---|---|---|']
ops=0
for path,item in api['paths'].items():
 for method,op in item.items():
  if method not in ('get','post','put','patch','delete'):continue
  ops+=1
  req=op.get('requestBody',{}).get('content',{}).get('application/json',{}).get('schema',{}).get('$ref','—').split('/')[-1]
  out=[]
  for code,r in op['responses'].items():
   if not code.startswith('2'):continue
   schema=r.get('content',{}).get('application/json',{}).get('schema',{}).get('$ref','body khác/không body').split('/')[-1]
   out.append(code+': '+schema)
  headers=[]
  for a in op.get('parameters',[]):
   if '$ref' in a:a=api['components']['parameters'][a['$ref'].split('/')[-1]]
   if a.get('in')=='header' and a.get('required'):headers.append(a['name'])
  rows.append('| '+' | '.join([op['operationId'],method.upper()+' `'+path+'`',', '.join(op.get('x-roles',[])),req,'; '.join(out),', '.join(headers) or '—'])+' |')
(P/'operation_catalog.md').write_text('\n'.join(rows)+'\n',encoding='utf-8')
print(json.dumps({'schemas':len(schemas),'operations':ops,'source_sha256':hash_}))
